#!/bin/sh
#
# Copyright (c) 2001-2003 Gregory M. Kurtzer
#
# Copyright (c) 2003-2011, The Regents of the University of California,
# through Lawrence Berkeley National Laboratory (subject to receipt of any
# required approvals from the U.S. Dept. of Energy).  All rights reserved.
#

. /warewulf/transports/http/functions

TMPFILE=`mktemp`

cd ${NEWROOT:-/}

while true; do
    for master in `echo $WWMASTER | sed -e 's/,/ /g'`; do

        rm -f /tmp/vnfs-download 2>/dev/null
        if ! mkfifo /tmp/vnfs-download 2>/dev/null; then
            echo "ERROR: Could not create the fifo!"
            exit 1
        fi

        gunzip < /tmp/vnfs-download 2>/dev/null | cpio -uidm --quiet 2>/dev/null &
        GZIP_PID=$!

        if wget -O /tmp/vnfs-download http://$master/WW/vnfs?hwaddr=$WWINIT_HWADDR; then
            wait
            echo
            # This is a cheesy way to see if the above wget worked... Ewww, I know...
            # But it does work.
            if [ -f "$NEWROOT/sbin/init" ]; then
                exit 0
            fi
        elif [ -n "$GZIP_PID" ]; then
            kill $GZIP_PID
        fi


    done
    throttled_sleep
done
echo

exit 1
